---
title: "School_diversity_Tidy_Tues"
author: "KGJ"
date: "9/23/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
list_of_packages <- c("janitor", "tidyverse", "lubridate", "ggthemes", "RColorBrewer", "sf", "maps","mapproj", "scales")
lapply(list_of_packages, library, character.only = TRUE)
```


## Quick look at School Demographics

Souce: Common Core of Data from the National Center for Education Statistics (NCES) via Washington Post, h/t #TidyTuesday

```{r get_data}
school_diversity <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")
states <- map_data("state")

# and manually scraped from https://www.census.gov/programs-surveys/school-finances.html
# *h/t https://twitter.com/HenriChung/status/1176634861378891776
budget <- read.csv("pp_expenditures.csv")
```


```{r explore}
school_diversity  %>%
  group_by(d_Locale_Txt, SCHOOL_YEAR) %>%
    summarise(total_population = sum(Total))
```


```{r wrangle }

#add state abbreviation to map data
states$ST<-state.abb[match(states$region,tolower(state.name))]

#add state abbreviation to budget data
budget$ST<-state.abb[match(budget$state,state.name)]

#

#states$abb <- state.abb[grep(states$region, state.name, ignore.case = TRUE)]

school_diversity$white_count <- school_diversity$White/100 * school_diversity$Total
  school_diversity$type <- word(school_diversity$d_Locale_Txt, sep = "-")

###
sd_st_type_long <- school_diversity %>%
  group_by(ST, SCHOOL_YEAR, type) %>%
    summarise(total_population = sum(Total), total_w_pop = sum(white_count))
  
sd_st_type_long$white_percentage <- sd_st_type_long$total_w_pop/sd_st_type_long$total_population

sd_st_type_long$year <- ifelse(sd_st_type_long$SCHOOL_YEAR == "1994-1995", 1995, 2017) 

sd_st_type_wide <- sd_st_type_long %>% pivot_wider(id_cols = c(ST,type), names_from = c(year, type) , values_from  = c(total_population,white_percentage))

sd_st_type_wide$city_rural_difference_1995 <- abs(sd_st_type_wide$white_percentage_1995_city - sd_st_type_wide$white_percentage_1995_rural)

sd_st_type_wide$city_rural_difference_2017 <- abs(sd_st_type_wide$white_percentage_2017_city - sd_st_type_wide$white_percentage_2017_rural)

sd_st_type_wide$city_rural_change <- sd_st_type_wide$city_rural_difference_2017 - sd_st_type_wide$city_rural_difference_1995

city_rural_change_budget_data <- left_join(sd_st_type_wide, budget, by = "ST")

city_rural_change_data <- left_join(states, sd_st_type_wide, by = "ST")

##
```



```{r plot}

city_rural_change_plot <-ggplot(city_rural_change_data, aes(long, lat, group=group, fill=city_rural_change)) +
  geom_polygon()+
  scale_fill_gradient2(low = "purple", mid = "white",  high = "orange", name  ="Divergence in Urban/Rural Demographics:
(higher number is increasing difference
in percent non-hispanic white students) ", breaks =  c(-0.16,0,.27), labels=scales::percent_format(accuracy = 1)) +
  coord_map("albers",  at0 = 45.5, lat1 = 29.5) +
  ggtitle(label = "Divergence in Urban and Rural 
Percentage Non-Hispanic White Students",
          subtitle = "1995 to 2017")  +
  labs(caption = "Source: National Center for Education Statistics via Washington Post, h/t #TidyTuesday") +
      theme(legend.position="bottom", plot.subtitle = element_text(face = "italic"))

city_rural_change_plot 

```

```{r save}
ggsave(filename= "nces.png", device = "png")
```



```{r plot2}
budget_plot <- city_rural_change_budget_data %>%
  ggplot(mapping = aes(x = city_rural_change, y = pp_expen_change)) + 
  geom_point() +
  geom_text(aes(label=ST),hjust=0, vjust=0)+ 
  geom_smooth(method = "lm") +
  labs(caption = "Source: National Center for Education Statistics via Washington Post, Census h/t #TidyTuesday") +
      theme(legend.position="bottom", plot.subtitle = element_text(face = "italic"))+
  ggtitle(label = "States with Higher Urban/Rural Demographic Divergence 
Invested Less in K-12 Education over time*",
          subtitle = "1995 to 2017
*Results not statistically significant at first glance
") +
  scale_y_continuous(name="Increase in State Per Pupil Spending",labels = scales::dollar) +
  scale_x_continuous(name  ="Urban/Rural Divergence in White Non-Hispanic", breaks =  c(-0.16,-.10,0,.1,.2,.28), labels=scales::percent_format(accuracy = 1))

budget_plot
```

```{r save}
ggsave(filename= "budget_plot.png", device = "png")
```
